
---
output:
  pdf_document: default
  html_document: default
header-includes: 
    - \usepackage{amsthm}
    - \usepackage{xcolor}
documentclass: article
<!---output: beamer_presentation--->
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(error=TRUE,        # Keep compiling upon error
                      collapse=TRUE,     # collapse by default
                      echo=TRUE,         # echo code by default
                      comment = "#>",    # change comment character
                      fig.width = 10,     # set figure width
                      out.width = "100%", # set width of displayed images
                      warning=TRUE,      # show R warnings
                      message=FALSE)     # show R messages

packageTest<- function(x)  {
    if (!require(x,character.only = TRUE))  {
      install.packages(x,dep=TRUE)
      if(!require(x,character.only = TRUE)) stop("Package not found")
    }
}

options(warn=-1)
```


<!--- Solution Region --->
<style>
#solution {
  background-color: #8FBC8F;
  border-style: solid;
  border-color: blue;
  margin-left: 20px;
  margin-bottom: 15px;
  padding: 5px;
}
</style>



<!---**Sommersemester 2019 |Studiengang Data Science | Hochschule Darmstadt **--->




\theoremstyle{break}
\newtheorem{auf}{Aufgabe}

\newcommand{\R}{{\sffamily R} }

\begin{centering}
%\vspace{-2 cm}
\Huge
{\bf Uebung 6}\\
\Large
Computational Statistics\\
\normalsize
Sommersemester 2019\\
April 15, 2019\\
J. Groos (FBMN, h\_da)\\
\end{centering}


\hrulefill

**Name:**

\hrulefill

```{r}
set.seed(42)
```

## A 1 
###a)

```{r}
gv <- runif(10000,min=0,max=1)
lambda <- 3
invexp <- -(1/lambda)*log(gv)
exp <- rexp(10000,lambda)

invpois = NULL
for (i in 1:10000){
j <- 0
U <- runif(1,0,1)
Y <- -(1/lambda)*log(U)
sum <- Y

while(sum < 1){
U <-  runif(1,min = 0,max = 1) 
Y <- -(1/lambda)*log(U)
sum <-  sum + Y
j <-  j + 1; 
}

invpois <- rbind(invpois,j)
}

pois <-  rpois(10000,lambda)

par(mfrow=c(1,2))

hist(invexp)
hist(exp)

hist(invpois)
hist(pois)

qqplot(invexp,exp)
qqplot(invpois,pois)
```

###b)

```{r}
u <- runif(10000,0,1)
v <- runif(10000,0,1)

bmnorm = cos(2*pi*u)*sqrt(-log(v))
norm <- rnorm(10000)

par(mfrow=c(1,2))
hist(bmnorm)
hist(norm)
qqplot(bmnorm,norm)
```

## A 2
###a)
```{r}
randomorg <- read.csv('randomorg.csv',header=FALSE)
randomorg <- randomorg[,"V1"]
```

###b)
```{r}
midsqr = function(seed, length) {
    ergebnis = c()
    for(i in 1:length) {
        value = seed * seed 
        seed = (value %/% 10000) %% 10000000
       ergebnis = c(ergebnis, seed/10000000)
    }   
    return(ergebnis)
}
midsqr = midsqr(2222222222222,10000)
```

###c)
```{r}
standardize <- function(x){(x-min(x))/(max(x)-min(x))}

baumannikov_zwirbler <- function(seed, n){
  if((seed %% 2) == 0){
    seed <- seed +1
  }
  start <- as.character((seed*n)^2)
  save <- c()
  for (i in 1:(n)){
    if (i == 1){
      x <- start
      k <- nchar(x)
      y <- as.numeric(substr(as.numeric(x), round(0.25*k), round(0.75*k)))
      save[i] <- y
    }
    else{
      x <- as.character((save[i-1]*n)^2)
      k <- nchar(x)
      y <- as.numeric(substr(as.numeric(x), round(0.25*k), round(0.75*k)))
      save[i] <- y
    }
  }
  return(standardize(save%%100))
}

baumannikov_zwirbler <- baumannikov_zwirbler(22222222, 10000)
```

###d)
```{r}
set.seed(22222222,kind='Mersenne-Twister')
mersenne <- runif(10000)

set.seed(22222222,kind='Super-Duper')
superduper <- runif(10000)
```

###e)
```{r}
par(mfrow=c(3,2))
hist(randomorg)
hist(midsqr)
hist(baumannikov_zwirbler)
hist(mersenne)
hist(superduper)

par(mfrow=c(1,1))
```